PREFIX moi: <http://www.sudan-government.com/ontologies/mistryofinteriorontology.owl#>
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>

SELECT (COUNT(?c) AS ?totalCitizens) WHERE { ?c rdf:type moi:Citizen . }