PREFIX moi: <http://www.sudan-government.com/ontologies/mistryofinteriorontology.owl#>
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>

SELECT ?citizen ?passport ?vehicleReg ?weapon WHERE { OPTIONAL{?citizen moi:hasPassport ?passport} OPTIONAL{?citizen moi:hasVehicleRegistration ?vehicleReg} OPTIONAL{?citizen moi:hasWeaponLicense ?weapon}}